### ISSUE TITLE
Remove Numbering

### ISSUE THREAD

**Issue by claytharrison** [TUW-GEO/eo-datascience#8]
Remove Numbering of the filenames

**Comment by MartinSchobben** [comment]
But check if numbering is required for eo datascience cookbook

**Comment by MartinSchobben** [comment]
Update: Numbering is currently required to generate the Jupyter Book TOC, but it is probably better to generate this TOC directly from the `_quarto.yml`

`_quarto.yml` (Quarto Book) -> `_toc.yml` (Jupyter Book)
